powerline/powerline

powerline/bindings/fish/powerline-setup.fish
powerline/bindings/zsh/powerline.zsh
powerline/commands/main.py
powerline/segments/shell.py
tests/lib/fsconfig.py

Bindings still use various variables, but they are no longer exported.
Ref #1239.

Remove all exports from shell bindings

---

tests/test_shells/postproc.py
tests/test_shells/test.sh

They are causing tests to fail, like in [build 1322.7](https://travis-ci.org/powerline/powerline/jobs/46443873).

When using `rc` remove “read() failed” messages

---

tests/lib/config_mock.py
tests/test_configuration.py

This commit refactors `TestVim` test class in test_configuration so that
1. `test_environ_update` does not leave state (value of `powerline_config_paths` 
global Vim variable) behind other tests can use.
2. `test_local_themes` does not rely on state left from `test_environ_update`, 
instead using new facility for providing needed value of 
`Powerline.get_config_paths` call. This facility will be used later in BAR 
tests.
Ref #1256

When testing Vim do not rely on test order and do not save state

---

powerline/bindings/tmux/powerline.conf
tests/test_in_vterm/test_tmux.py

This variant reduces the number of commands tmux needs to run in `powerline.conf`.

Another attempt to stabilize vterm tests

---

docs/source/configuration.rst

The "Colorschemes" link on the configuration page leads to Color definnitions instead of Colorschemes.

Fix link to colorschemes section

---

powerline/segments/common/bat.py
tests/test_in_vterm/test.sh
tests/test_in_vterm/test_tmux.py

Unlike previous attempts this uses a well-known “rerun the failing test” path.

Stabilize vterm tests

---

client/powerline.sh
powerline/bindings/shell/powerline.sh
tests/install.sh
tests/test.sh
tests/test_in_vterm/test.sh
tests/test_in_vterm/test_tmux.py
tests/test_lib.py
tests/test_shells/postproc.py
tests/test_shells/run_script.py
tests/test_shells/screenrc
tests/test_shells/test.sh
tests/test_shells/zsh_test_script.zsh

Dash tests still do not work, but now they do not work completely, not “are not stable” (#931). Alongside with other small fixes this PR switches from screen for shell tests to pexpect.

Add some fixes for testing from ebuild

---

powerline/config_files/colorschemes/default.json

Tried setting up the email_imap_alert with the default scheme, but it crashed saying that the highlight color group 'email_alert' couldn't be found. This seems to fix it.

Add warning:regular to default color scheme

---

powerline/config_files/colorschemes/default.json
powerline/config_files/colorschemes/vim/__main__.json
powerline/lint/checks.py
powerline/lint/markedjson/error.py
powerline/lint/spec.py

It appears that `warning:regular` group was missing, so email_imap segment did not work (#1323, #1320) and when running under superuser user segment was not highlighted properly.
This PR adds missing highlight groups and also makes sure that `powerline-lint` will be able to catch such problems in the future.

Add missing highlight groups

---

powerline/vim.py
tests/test_foreign_stl_override.vim

This normally should not happen because &l:stl should be powerline-controlled,
but some plugins do this.
Fixes #1347

Fix warning when &l:statusline is set to a unicode value

---

powerline/bindings/shell/powerline.sh
tests/test_shells/test.sh

Fixes two errors that occur while using Powerline with the dash shell under Mac OS X.
**Problem:** Execution of the mktemp command fails.
**Cause:** mktemp requires a mandatory argument on OS X.
**Solution:** Provide a template using the -t option. While it is a deprecated option on Linux, it is still supported and provides compatibility with other systems.
**Problem:** The powerline executable fails to be called because its command line unexpectedly contains spaces.
**Cause:** The _POWERLINE_JOBS variable contains spaces because the wc command returns spaces before the number on OS X.
**Solution:** Trim the spaces before assigning the value to the variable.

Fix dash bindings on OS X

---

docs/source/usage/wm-widgets.rst
powerline/bindings/bar/powerline-bar.py
powerline/renderers/bar.py
powerline/segments/i3wm.py
tests/test_segments.py

Replaces #1366 which contains at least one error (Python-2.6 does not support `func(expr for i in iterable)`: need more parenthesis) and a number of style mistakes.
Provided tests should’ve catched the error if it was not fixed in c02516a4437c0d94f6585dce65ca349c6b399120.

Switch the underlying i3-IPC layer and deprecate i3bgbar bindings

---

powerline/segments/common/sys.py

It now replaced psutil.BOOT_TIME attribute.
Fixes #1391

Use psutil.boot_time() function if appropriate

---

docs/Makefile
docs/source/powerline_automan.py

Fix manpage generation with Python 3 and allow packagers to select which version of sphinx-build (python2 ou 3) they want to use. Fixes issue #1388.

Fix manpage generation with python3

---

.travis.yml
tests/test.sh

All of them were whitelisted:
- Tcsh was whitelisted in travis-ci/travis-ci#3882.
- Mksh was whitelisted in travis-ci/travis-ci#3881.
- Busybox was whitelisted in travis-ci/travis-ci#3880.
- Socat was whitelisted in travis-ci/travis-ci#3883.

Do not use tcsh, mksh, busybox and socat from deps

---

powerline/segments/common/net.py
tests/test_segments.py

This pull requests adds the option to specify `interface='default_gateway'` to the `internal_ip` segment. This displays the IP address of the interface connected to the [default gateway](https://en.wikipedia.org/wiki/Default_gateway).
**Motivation:** I own a MacBook Pro running OS X. Sometimes I am connected to the Internet via Ethernet (interface `en0`), other times via wireless (interface `en1`). Either way, I want to see the IPv4 address of the interface through which my Internet traffic is going.
**Details:** The default behavior for OS X is that IPv4 addresses are configured through DHCP, and only assigned if the interface is connected. But IPv6 addresses are assigned through [stateless address autoconfiguration](https://en.wikipedia.org/wiki/IPv6#Stateless_address_autoconfiguration_. …

Add option to detect internal_ip interface from default gateway

---

docs/source/installation/osx.rst

Fix typo (missing letter) in installation/osx.rst

---

docs/source/troubleshooting.rst

In regards to #684 , this might be useful to have in the tips & tricks.
Apparently, my editor also trimmed some whitespace, sorry about that. ;)

Added tips for Urxvt compiler flags

---

.travis.yml
docs/source/develop/segments.rst
powerline/commands/main.py
powerline/renderers/tmux.py
tests/install.sh

Tmux-2.1 appears not to output leading `%` when using `tmux display -p '#D'`. 
This change changes type of the `pane_id` argument: leading `%` turns it into 
a literal string, number in front makes it be parsed as a JSON number.
Fixes #1470

Support tmux-2.1

---

powerline/segments/common/env.py
tests/test_segments.py

Conda environments are pretty much the same as virtualenvs, so I just added a check for them there. One could put it in a separate segment, but I think it fits naturally here.

Show conda environment in virtualenv segment.

---

powerline/segments/common/env.py
tests/test_segments.py

If true, this argument hides `@` and the following characters from the user
name.
Fixes #1420
Closes #1426

Add hide_domain argument to common.env.user segment

---

MANIFEST.in

As introduced in #1449 a systemd's `.service` file was included in `dist/systemd`.
However this folder was not included in `MANIFEST.in`.

Include dist folder to MANIFEST.in

---

powerline/segments/common/bat.py

Fix a bug where the `online` property is checked inside battery
instead of AC.
As specified in issue #1483, `online` is found only inside
`/sys/class/power_supply/AC<x>/` directories, and equals `1` when cable is
plugged, and `0` when unplugged.

Fix #1483 -- [Battery - Linux] Fix AC status fetch

---

powerline/config_files/colorschemes/vim/__main__.json
powerline/config_files/themes/vim/tabline.json
powerline/listers/vim.py
tests/test_tabline.vim
tests/vim.py

This pull request dramatically improves the experience of using the tabline with `showtabline=2` set. #1281 discusses an issue with Powerline flickering that is only caused when the bufferline is always displayed (with only one tab).
This is due to the prior usage of `vim_getbufoption(segment, 'buflisted')` in the conditionals of the bufferlister segment. Querying the buffer options through the vim python module's `option` attribute caused vim to think it needed to update the tabline for every keystroke after any event that changed the buffer's options.
Using the vim module's `eval` method to directly use the `buflisted(nr)` vim method instead does not cause vim to update the tabline after every keystroke, but rather after events that would change that status, thus fixing the flickering …

Tabline and bufferlister updates

---

powerline/segments/common/players.py

Otherwise the mpd function will fail when it encounters non-ASCII metadata as it tries to do a unicode.format() and attempts to decode the incoming data as ASCII, throwing a UnicodeDecodeError exception.
Fixes #1500 
Note that `python-mpd` (as opposed to `python-mpd2`) does not support `client.currentsong()`, so I don't think that actually works anymore.  Otherwise I'd be happy to a `try / except TypeError` + redo without the `use_unicode` parameter.  `python-mpd2` is happy with the extra argument under Python 3 (it's just mostly a no-op).

[Players - mpd] Use Unicode where available

---

powerline/bindings/tmux/powerline-base.conf

It is incorrect to set it at all because what powerline outputs depends on 
locale used, and if locale is utf8 then tmux should already set this option.

Remove status-utf8 option

---

docs/source/develop/segments.rst

* The display_condition key in the docs was rendered as
'display_condition`' due to a small typo. This commit fixes that.
Signed-off-by: mr.Shu <mr@shu.io>
-----------------
Note that this problem can be seen at https://powerline.readthedocs.org/en/latest/develop/segments.html#dev-segments-seg-contents where I noticed it too.

docs: Fix a small typo in develop/segments.rst

---

powerline/segments/common/bat.py

* In #1499 a change was introduced that made use of the "Discharging"
status of a battery in order to detect whether the AC power is
available.
The DBus part of the function that gets this data, however, stayed
unchanged. In order to keep it consistent this commit changes it in
such a way that it preforms the same function as the code introduced
in #1499 by checking for the Discharging state of the battery as
described here:
http://upower.freedesktop.org/docs/Device.html#Device:State
Signed-off-by: mr.Shu <mr@shu.io>

fix: Make dbus battery status consistent

---

powerline/bindings/wm/__init__.py

When there is a primary output set the current regex doesn't match that line / output.

Fix bug in xrandr output detection

---

docs/source/installation/osx.rst

Flag `--override-system-vim` is deprecated.
Fixes #1526.

Update command used to install macvim with brew

---

powerline/segments/common/bat.py

Fixes a bug introduced by #1531 where a typo in the filepath for battery energy levels leads to a `FileNotFoundError`.

Fixes bug in multi-battery support

---

docs/source/usage/other.rst

This PR is improving documentation about how to integrate Powerline with iPython. Tested on Arch Linux and Ubuntu.

More specific instructions for iPython

---

powerline/lib/encoding.py

Adds code to check if locale has the 'LC_MESSAGES' attribute before
executing the following line of code:
locale.getlocale(locale.LC_MESSAGES)[1]
Fixes #1555

Fix LC_MESSAGES AttributeError

---

powerline/segments/common/players.py

Use proper dictionary for getting “elapsed” value in mpd bindings

---

powerline/config_files/colorschemes/default.json
powerline/config_files/colorschemes/solarized.json
powerline/config_files/colorschemes/vim/solarized.json
powerline/config_files/colorschemes/vim/solarizedlight.json
powerline/config_files/themes/ascii.json
powerline/config_files/themes/powerline.json
powerline/config_files/themes/powerline_unicode7.json
powerline/config_files/themes/shell/default.json
powerline/config_files/themes/unicode.json
powerline/config_files/themes/unicode_terminus.json
powerline/config_files/themes/unicode_terminus_condensed.json
powerline/lib/vcs/git.py
powerline/segments/common/vcs.py
powerline/segments/vim/__init__.py
tests/test_lib.py
tests/test_segments.py

Some version control systems have an area where changes can be stored as temporary work in progress instead of publishing them to the history, such as Git's "stash" or Mercurial's "shelve". Their count neatly displayed in powerlines similar to the branch name could remind a developer that there are still open ends left in his repository.
This pull requests sets up a segment doing so and provides an implementation for Git repositories. As it is my first take on the powerline source code, comments are much appreciated.

provide a VCS stash segment

---

scripts/powerline-daemon

The number `1` for backlog is quite small.
On my FreeBSD box, I got this message:
```
Mar 28 19:01:43 imfsa kernel: sonewconn: pcb 0xfffff802088b25a0: Listen queue overflow: 2 already in queue awaiting acceptance (32 occurrences)
```
and
```
% netstat -na | grep fffff802088b25a0
ffffff802088b25a0 stream      0      0 fffff802088b25a0        0        0        0 /tmp/powerline-ipc-1001
```
Increasing the backlog number can solve the queue overflow problem.

Increase socket backlog number for `powerline-daemon`

---

powerline/segments/vim/__init__.py

Using str() on a bytestring produces the repr on Python 3, not some
implicitly decoded string. So use an explicit decode instead.
Fixes #1613.

Fix trailing whitespace segment on Python 3.

---

docs/source/installation.rst
powerline/lib/vcs/mercurial.py
tests/test_lib.py

This wrapper uses the command server without tying it to the mercurial internals, which means it can support Python 3 and use a more liberal license.
Fixes #1675 and maybe fixes #1646.

Use hglib instead of mercurial directly.

---

docs/source/configuration/reference.rst
powerline/renderer.py
powerline/theme.py
tests/test_configuration.py

Defaults to previous behaviour (length 1).
I'm not sure if anyone else would be interested in this change, but the compulsory padding was bugging me so here it is.

Make length of `output_padding` in renderer controllable

---

powerline/segments/common/bat.py

If your battery is broken this segment crashes with a ZeroDivisionError

Prevent divide by zero battery capacity

---

docs/source/configuration/reference.rst

`segments_list` type throws an Error:
> Unknown segment type: segments_list
Correct type is `segment_list`.
This fixes the docs.

fix incorrect segment type `segments_list` - should be `segment_list`

---

powerline/bindings/tmux/__init__.py

See #1727.
It seems that [tmux/tmux](https://github.com/tmux/tmux/branches) is only developed on a single `master` branch, so having that comparison hardcoded is probably appropriate, but hardcoding the latest tmux version to be bumped every release seems less-than-ideal to me, open to suggestions on that.
Since tmux releases may prompt changes to the tmux bindings anyhow though, it  may be 'good enough' but I suspect something better should be done in `powerline/bindings/config.py` to snap to the latest version based on the available tmux.conf's in the binding directory.

Assume latest tmux version if -V returns 'master'

---

powerline/bindings/fish/powerline-setup.fish

For some reason, fish 2.5.0 freaks out under certain circumstances if
your `config.fish` calls `eval` at any point. For equally mysterious
reasons, replacing `eval` with `source` makes things work again.
See fish-shell/fish-shell#3809 for more details.

Fish bindings: replace eval with source

---

powerline/lib/vcs/mercurial.py

Current variant spawns way too many hg instances which are not collected until 
Vim exits.

Do not forget to collect mercurial servers

---

docs/source/usage/wm-widgets.rst
powerline/bindings/i3/powerline-i3.py
powerline/renderers/i3bar.py

Specifically:
- Do not log exceptions to the same location data is output.
- Fix format, i3bar is no longer using “pseudo-JSON”, also not sure whether it 
ever used format `[[right list], [left list]]`, but it definitely does not 
now.
- i3bgbar branch is no longer available.
- Yet i3wm supports background color, just with the different key (`background` 
vs `background_color`).

Fix i3 bar bindings

---

docs/source/installation/linux.rst

`~/.fonts/` has been deprecated in favour of `~/.local/share/fonts/`.
References:
- https://github.com/behdad/fontconfig/blob/master/fonts.conf.in#L29
- https://lists.freedesktop.org/archives/fontconfig/2014-July/005270.html
Fixes #1793

Replace ~/.fonts with ~/.local/share/fonts in help

---

powerline/segments/common/players.py

changed choosing logic. because:
spotify on OS X does not support dbus message so applescript had to be used.
other system does not support applescript so dbus has to be used.

change spotify to use applescript on OS X

---

powerline/segments/common/players.py

Because duration of current track is returned by milliseconds from spotify.
it should be divided by 1000 before being displaying.

fix spotify applescript track length

---

docs/source/usage.rst

In the first paragraphof usage.html: "s/Presense/Presence of Python support in vim..."

Fixes typo in documentation

---

powerline/segments/common/bat.py

Windows Subsystem for Linux abstracts the batteries in a laptop
into a single battery, and only states the percent charge via
/sys/power_supply/battery/capacity.  If dbus is unavailable,
and no charge/energy readings are available for any power supply,
search for the first power supply that has a capacity file, and use it
(and its state) as the battery status.
Tested on a Surface Book 2 running Windows 10 with  Windows
Subsytem for Linux Ubuntu 16.04

Check for battery percentage if no charge/energy

---

powerline/segments/common/players.py

Updating linux dbus config according to Spotify client version: 1.0.69.336.g7edcc575.
Now player segment works as expected.

(fix) updated linux spotify app dbus config

---

docs/source/troubleshooting/osx.rst

I seems that disable transparency is no more mandatory to keep good colors.

Transparency doesn't need to be disabled

---

powerline/bindings/wm/__init__.py

This should fix Json error with i3bar binding #1875.
I reproduce the bug by having i3-py and i3ipc at the same time. In get_i3_connection() we prioritize i3ipc which is good. But in i3_subscribe we prioritize i3-py which make a confilct.
I've tested with only i3-py, only i3ipcand with both.

Fix for i3 if you have i3-py and i3ipc install

---

powerline/bindings/fish/powerline-setup.fish

* Fixes #2013 by implementing the function `fish_mode_prompt` in the fish binding.
* Remove hacky (and buggy) `_powerline_columns` and replace it by `_powerline_columns_fallback`

Fix #2013; Improve fish binding

---

powerline/bindings/tmux/__init__.py

Fixes issue caused by tmux version naming changing from `3.0-rc` to `next-3.1`, caused by this commit: https://github.com/tmux/tmux/commit/e7a530fe4c0f8e0f807daf6a1b80d86c67c93e1b
This is for issue #1992 
With that version, the version is in an unexpected format:
```
bbyers ~ $ tmux -V
tmux next-3.1
```
Causing an error when powerline attempts to return an in for the major version number:
```
bbyers ~ $ powerline-config tmux setup
Traceback (most recent call last):
File "/home/bbyers/.local/bin/powerline-config", line 22, in <module>
args.function(pl, args)
File "/home/bbyers/.local/lib/python3.5/site-packages/powerline/commands/config.py", line 15, in __call__
self.function(*args, **kwargs)
File "/home/bbyers/.local/lib/python3.5/site-packages/powerline/bindings/config.py", line 184, in …
```

Parse out letters in maj. version string

---

powerline/config_files/colorschemes/solarized.json

Current settings leads to the following under tmux (on the right side):
After this modification, it looks like:

Fix divider background color for tmux solarized

---

docs/source/usage/other.rst
powerline/bindings/ipython/post_0_11.py

The method used for `since_5` does not work, but `since_7` does, however it is not documented.
I personally haven't found `c = get_config()` to be useful once you have generated the default `~/.ipython/profile_default/ipython_config.py` file.
Since `c.TerminalInteractiveShell.simple_prompt` is set to `False` by default, it's not worth mentioning it.  There's many other things that **can** break if you change the default config options too.  Additionally, `simple_prompt=True` doesn't fatally break anything— just make things less pretty.  So it'd be better to not have that, but mention if things don't look pretty to make sure they didn't change that default.
Additionally updated `post_0_11.py` to use `since_7` (given that most people using a later version than 0.11 are probably using 7), …

Update Powerline for ipython >=7

---

README.rst

This isn't super important and would be considered a low priority change - however there is a lot of people googling for the same answer that this one line could cover.

Update to include default path to powerline_root for apt-get

---

powerline/lib/vcs/git.py

Adding --no-optional-locks will cause fewer interference with other git clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powerline/powerline/2098)

Use `--no-optional-locks` to reduce conflicts with other git editors

---

powerline/segments/common/sys.py

Although the docs for psutil say 0.0 is a nonsense value that's returned
first and supposed to be ignored, but on a relatively idle system it
will actually return 0.0 occasionally after that. So at the expense of
displaying that "nonsense value" when the statusbar first loads, this
change gets rid of the visual disruptions of having the segment pop out
and back in periodically.
Fixes #2110.

Render cpu_load_percent segment even when psutil returns 0.0

---

.github/workflows/main.yaml

Requires a secret named PYPI_TOKEN containing a valid PyPI API token.
Note that this drop support for Python 2.6 as GitHub Actions only
supports Python 2.7+.
Fixes #2116

Implement GitHub actions for build and publish

---

powerline/bindings/vim/plugin/powerline.vim

Python 2 is EOL, so it makes more sense to use Python 3 as the preferred version of Python rather than just fall back on it.

Prefer Python 3 in the Vim plugin

---

powerline/segments/common/sys.py
tests/test_python/test_segments.py

This mainly addresses #1859 and provides a reasonable standard way of showing the uptime.
Now, this format
- Does show a time units with 0 as long as there are bigger time units (e.g. will show 0 seconds if there are minutes but not days if your uptime is below a day)
- Shows 2 digits for seconds and minutes and thereby prevents frequent changes in size here (I didn't add that for hours because I think these 2 size changes/day are not distracting)
I would be happy if this could get merged and finds it way into the repo

Updated uptime segment to have show time in a better way

---

powerline/vim.py

Ref #2125
I looked at `statusline()`, and it seems that it tries to render a current window if `self.win_idx(None)`  returned `None`. So I did the same in `tabline()` for consistency.

Fallback to a current window in tabline()

---

powerline/bindings/zsh/__init__.py
powerline/segments/common/env.py
tests/test_python/test_segments.py

Went a bit through the project backlog.
This fixes #2094 and includes tests for the additional behaviour introduced, namely going up a directory if a venv name is on a blacklist (which is useful if all your venv's are called `venv` and the meaningful name is the project dir above).
This list can be configured, currently the blacklist is `venv` and `.venv`.
I doubt that there are concerns with these 2 names, however if someone wants to have additional default venv names, I can also include them.
PS: I'd appreciate getting a `hacktoberfest-accepted` label for this PR

Fix non-meaningful venv names.

---

powerline/lint/spec.py

There is a small typo in powerline/lint/spec.py.
Should read `provided` rather than `proided`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, proided -> provided

---

powerline/config_files/colorschemes/default.json
powerline/config_files/themes/wm/default.json
powerline/listers/i3wm.py
powerline/segments/i3wm.py
tests/modules/__init__.py
tests/test_python/test_segments.py

* added an `active_window` segment
* added highlight groups `workspace:urgent`, `workspace:visible`, `workspace:focused` as alternatives to the `w_*` highlight groups
* added options to the `workspaces` segment
* `format='{name}'`: formatting options for displaying a single workspace
* `icons=WS_ICONS`: a dictionary mapping window titles to icons, for displaying currently running programs on a specific workspace (populates the fields `icon` and `multi_icon` in the `format` string.
* `sort_workspaces=False`: If set to true, workspaces are sorted (naturally) according to their name
* `show_output=False`: If multiple outputs are connected, displays a segment for each output before the workspaces of the corresponding outputs.
* `priority_workspaces=[]`: A list of workspaces that are always …

i3 segments rework

---

powerline/bindings/zsh/powerline.zsh

If powerline-config isn't on $PATH, GNU which will output "no
powerline-config in ($PATH)" to stderr, which we previously weren't
silencing.

powerline.zsh: squelch which output.

---

docs/source/installation.rst
docs/source/installation/linux.rst
docs/source/installation/osx.rst

Replace `git` protocols with `https` protocol.
git:// is deprecated from Github starting from Jan. 11th, 2022.
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

Remove git protocol
