powerline/lib/dict.py, powerline/lint/__init__.py, powerline/lint/markedjson/error.py, powerline/lint/markedjson/markedvalue.py
Apparently powerline-lint was not bothering to check user configuration.
=> Fix powerline-lint

docs/source/powerline_automan.py, powerline/commands/daemon.py, scripts/powerline-daemon
=> Allow --foreground to be used with --replace

powerline/bindings/vim/__init__.py
=> Make sure python_to_vim function is able to format lists

docs/source/usage/shell-prompts.rst, powerline/bindings/config.py, powerline/bindings/tmux/powerline.conf, powerline/commands/config.py, tests/install.sh, tests/lib/terminal.py, tests/lib/vterm.py, tests/run_vterm_tests.sh, tests/test_in_vterm/test.sh, tests/test_in_vterm/test_tmux.py
=> Fix tmux bindings and add functional test for tmux

docs/source/usage/wm-widgets.rst, powerline/bindings/bar/powerline-bar.py, powerline/bindings/i3/powerline-bar.py, powerline/commands/main.py, powerline/lib/encoding.py, powerline/renderers/bar.py, scripts/powerline-daemon, scripts/powerline-render, tests/test_configuration.py
=> Add BAR support with i3 bindings

client/powerline.c
After some debugging, I found that the Powerline client on my OS X was not connecting to the daemon. After some more debugging, it turned out that it was an incorrect `sockaddr_un` size being passed to `connect`.
This pull request should fix this for non-Linux platforms. If the platform defines `SUN_LEN`, we'll use that, otherwise fall back to the size of the struct. No changes were made for Linux.
This code was tested on OS X Mavericks (10.9) and CentOS 7.
On a side note, would you be opposed to me adding more options for debugging the clients? I know the goal is to keep them small and fast, but it was confusing for a newcomer like me to be "using the daemon" but still have a slow prompt. I'd have to think about how it could be implemented, but it would be nice to know that the client …
=> Fix socket address size on non-Linux platforms.

tests/test_in_vterm/test_tmux.py
=> Wait more before failing tmux vterm tests

powerline/bindings/zsh/powerline.zsh
This way there appear no duplicates.
=> Use special function for appending to precmd_functions

powerline/lint/markedjson/error.py
=> Always write str() objects to the stream in echoerr

docs/source/installation/linux.rst
=> Add note on outdated ArchLinux AUR Packages.

docs/source/installation/linux.rst
Reverts powerline/powerline#1343
=> Revert "Add note on outdated ArchLinux AUR Packages."

tests/test_cmdline.py
=> Fix main arguments parser tests

.travis.yml, tests/install.sh, tests/run_vim_tests.sh, tests/test.sh
Should speed up builds. A number of packages are missing, so they are now compiled by https://github.com/powerline/bot-ci.
=> Switch to container-based infrastructure

powerline/config_files/colorschemes/default.json, powerline/config_files/colorschemes/solarized.json, powerline/segments/common/net.py, tests/test_segments.py
=> Use different highlight group for network_load divider

powerline/bindings/tmux/powerline-base.conf, powerline/bindings/tmux/powerline_tmux_1.7_plus.conf, powerline/bindings/tmux/powerline_tmux_1.8_plus.conf, powerline/lib/overrides.py, powerline/renderers/tmux.py, tests/lib/terminal.py, tests/lib/vterm.py, tests/test_in_vterm/test.sh, tests/test_in_vterm/test_tmux.py
=> Add support for truncating tmux segments

powerline/segments/common/mail.py
=> Add support for non-SSL IMAP4 connections

docs/source/develop/segments.rst, powerline/config_files/themes/vim/tabline.json, powerline/lint/__init__.py, powerline/lint/checks.py, powerline/renderer.py, powerline/segment.py, powerline/segments/vim/__init__.py, tests/test_empty_encoding.old.vim, tests/test_segments.py, tests/test_tabline.vim
=> Add support for clicking tabs in Vim

docs/source/troubleshooting.rst, powerline/bindings/tmux/powerline-base.conf, powerline/bindings/tmux/powerline_tmux_1.7_plus.conf, powerline/bindings/tmux/powerline_tmux_1.8_plus.conf, powerline/renderers/tmux.py
=> Workaround tmux bug: additional space in display -p '#D' output

powerline/segments/i3wm.py, tests/test_segments.py
=> Add 'output' option to segments.i3wm.workspaces

powerline/segments/common/players.py
=> Fix support for passworded connections in mpd+python-mpd* player seg

powerline/dist/systemd/powerline-daemon.service
OK, done and tested. I didn't set any `Restart=` since I don't know if it should be restarted by sytemd on failure, right now it just fails, if it fails.
=> Added a systemd service, fixes #1447.

docs/source/installation.rst
=> Do not state that patched font does not work for rxvt-unicode

tests/test_segments.py
See https://bitbucket.org/pypy/pypy/issues/2161/pypy3-strftime-does-not-accept-unicode
=> Skip date test on PyPy3

.travis.yml, docs/source/configuration/local.rst, docs/source/configuration/reference.rst, powerline/__init__.py, powerline/bindings/config.py, powerline/lint/__init__.py, powerline/lint/checks.py, powerline/lint/spec.py, powerline/listers/vim.py, powerline/segments/vim/__init__.py, powerline/vim.py, tests/test_logging.py
Allow logging to multiple locations at once and also log to locations other then one stream (selected by powerline and not by user) or one file.
=> Add more logging options

docs/source/troubleshooting/osx.rst
Add a iTerm fix solution from https://github.com/powerline/fonts/issues/44
=> Add iTerm fix solution.

powerline/segments/common/bat.py
Support AC adapters that are listed in sysfs as "ADPx" in addition
to "ACx".  The name comes straight from ACPI, and unfortunately it
is extremely inconsistent across manufacturers.
Fixes #1498
That line is getting a bit long, but flake8 didn't seem to want to complain.
=> [Battery - Linux] Allow AC power to be named "ADPx"

powerline/segments/common/bat.py
Adding multiple battery support to DBUS+UPOWER and /sys battery interfaces.  Fixes #1288 and hopefully mirrors #1522.
=> Multiple Battery Support

powerline/lib/shell.py, tests/lib/__init__.py, tests/test_lib.py
=> Make Popen.communicate receive only bytes

powerline/config_files/themes/ascii.json, powerline/config_files/themes/powerline.json, powerline/config_files/themes/powerline_unicode7.json, powerline/config_files/themes/unicode.json, powerline/config_files/themes/unicode_terminus.json, powerline/config_files/themes/unicode_terminus_condensed.json, powerline/segments/i3wm.py, tests/test_segments.py
Tests are missing but this needs to wait until acrisci/i3ipc-python#26 gets merged anyway
=> Add segments.i3wm.scratchpad

docs/source/installation.rst, powerline/listers/i3wm.py
update dependencies for xrandr and i3ipc, fix a typo
=> Fix and update documentation concerning i3wm

powerline/bindings/ipython/post_0_11.py, powerline/bindings/ipython/pre_0_11.py, powerline/bindings/ipython/since_5.py, powerline/ipython.py, powerline/renderer.py, powerline/renderers/ipython/__init__.py, powerline/renderers/ipython/pre_5.py, powerline/renderers/ipython/since_5.py, powerline/renderers/shell/__init__.py, tests/common.sh, tests/test_provided_config_files.py, tests/test_shells/test.sh
=> Add support for IPython-5

powerline/bindings/bash/powerline.sh, powerline/bindings/fish/powerline-setup.fish, powerline/bindings/rc/powerline.rc, powerline/bindings/shell/powerline.sh, powerline/bindings/tcsh/powerline.tcsh, powerline/bindings/zsh/powerline.zsh
Also closes #1637 in most cases
=> Use $TMUX_PANE if it is defined

powerline/bindings/zsh/powerline.zsh, tests/test_shells/input.zsh
=> Provide explicit scope information in powerline.zsh

powerline/segments/common/bat.py
Both "charge" (µAh) and "energy" (µWh) represents "capacity"
of battery in linux.
More details can find here:
https://github.com/torvalds/linux/blob/master/Documentation/power/power_supply_class.txt
Fixes #1605.
=> Fix filenames for linux power supply class in battery segment.

docs/source/configuration/reference.rst, powerline/__init__.py, powerline/bindings/awesome/powerline-awesome.py, powerline/bindings/awesome/powerline.lua, powerline/bindings/bar/powerline-bar.py, powerline/bindings/bash/powerline.sh, powerline/bindings/config.py, powerline/bindings/fish/powerline-setup.fish, powerline/bindings/rc/powerline.rc, powerline/bindings/shell/powerline.sh, powerline/bindings/tcsh/powerline.tcsh, powerline/bindings/wm/__init__.py, powerline/bindings/wm/awesome.py, powerline/bindings/zsh/powerline.zsh, powerline/commands/main.py, powerline/config_files/config.json, powerline/lint/__init__.py, scripts/powerline-daemon, scripts/powerline-render, tests/run_awesome_tests.sh, tests/test_awesome/path/awesome-client, tests/test_awesome/powerline/config.json, tests/test_awesome/powerline/themes/wm/default.json, tests/test_awesome/powerline/themes/wm/dvi.json, tests/test_cmdline.py, tests/test_shells/test.sh
Also adds functional tests for awesome bindings.
Replaces #1641
=> Use powerline daemon for running awesome bindings

powerline/bindings/bash/powerline.sh
=> Check that bash has (no) $PIPESTATUS support before using it

setup.py
=> Specify argparse dependency

powerline/segments/common/players.py
I have added the dbus elapsed line for all dbus players.
=> Adding elapsed time to dbus players

powerline/segments/common/players.py
added elapsed time to spotify applescript player segment
tested on OS X 10.12.6 Spotify 1.0.58
=> added elapsed time to spotify applescript player segment

powerline/bindings/bash/powerline.sh
=> Do not use negative indexes

powerline/segments/common/vcs.py
=> Fix data type in branch segment documentation

docs/source/configuration/segments/vim.rst, powerline/segments/vim/plugin/ale.py
This segment has the same functionality and interface as the Syntastic
Vim segment plugin, and the code is largely adapted from it
=> Added Vim segment plugin for the Asynchronous Linter Engine (ALE)

powerline/bindings/config.py, powerline/renderers/tmux.py
=> Added support for truecolor in tmux

powerline/segments/common/players.py
This PR is based off #1870 and adressing Issue #1754
=> (fix) updated spotify segment to support both new and old protocol

docs/source/installation.rst
Including `, the` for readability
=> grammar fix

powerline/config_files/themes/ascii.json, powerline/config_files/themes/powerline.json, powerline/config_files/themes/powerline_terminus.json, powerline/config_files/themes/powerline_unicode7.json, powerline/config_files/themes/unicode.json, powerline/config_files/themes/unicode_terminus.json, powerline/segments/vim/__init__.py
Closes https://github.com/powerline/powerline/issues/1916
=> Recognize Terminal-Job mode (added in vim 8)

powerline/segments/common/players.py
- mpc current format only used to get album info
- state, artist, title, total and elapsed now gotten from mpc command
with no extra parameters and a regular expression
- state uses convert state to sanitize the state from mpc
Ref #2010
=> Added mpc support for state and elapsed

powerline/bindings/lemonbar/powerline-lemonbar.py, tests/test_bar/test.sh
=> support vertically-aligned multi-monitor setups in lemonbar

client/powerline.sh, powerline/bindings/bash/powerline.sh, powerline/bindings/shell/powerline.sh, tests/shlib/common.sh, tests/shlib/vterm.sh, tests/test.sh, tests/test_awesome/test.sh, tests/test_bar/test.sh, tests/test_in_vterm/test_shells.sh, tests/test_in_vterm/test_tmux.sh, tests/test_in_vterm/test_vim.sh, tests/test_shells/test.sh
Currently only changed tests/test.sh and tests/test_bar/test.sh .
Need to check how travis handles this.
=> Addressing #2027 gradually - use command -v

powerline/segments/common/players.py
Using the segment `powerline.segments.common.players.dbus_player` does
not work when a player has not been specified explicitly. In such a
case, with this PR, the segment will automatically choose the 1st media
player that implements "org.mpris.MediaPlayer2.Player".
This can be useful in displaying tracks from media players in powerline
without having to know the corresponding media player's properties
before-hand.
For example, this also works for displaying media tracks being played
on Google Chrome (since Chrome implements D-Bus interface) on YouTube,
etc.
Also see #2083.
=> Select a D-Bus media player automatically

powerline/segments/common/time.py, tests/test_python/test_segments.py
Closes https://github.com/powerline/powerline/pull/1337, closes https://github.com/powerline/powerline/pull/1395, closes  https://github.com/powerline/powerline/pull/2096.
=> Add timezone argument to date and fuzzy_time segments

powerline/segments/common/players.py
I just stumbled upon #1829 on my Mac (for Spotify though, not for iTunes).
As the fix was quite easy, I wanted to open a PR for it and get it merged in
=> Fix elapsed time resulting in ValueError on macOS (in German) for player segments

setup.py
This is most definitely going to be true in future also.
=> Factored statement always executed in conditional

docs/source/develop/segments.rst, docs/source/usage/wm-widgets.rst, powerline/bindings/wm/__init__.py, powerline/listers/i3wm.py, powerline/segments/i3wm.py, tests/test_python/test_listers.py, tests/test_python/test_segments.py
=> Use updated i3ipc syntax in i3 segments/listers

docs/source/installation/osx.rst, docs/source/troubleshooting.rst, docs/source/usage/shell-prompts.rst
After reviewing the GitHub issues to improve my zsh performance, I found these comments to be helpful.  Adding them to the docs for future users.
Apologies for not squashing before PR, I'm working entirely from the web UI.
=> Added tips to installation docs
